2025-03-13 00:49:24,739 - INFO - The program has begun
2025-03-13 00:49:24,739 - ERROR - The error occured:division by zero
2025-03-13 00:49:24,739 - ERROR - Exception details:
Traceback (most recent call last):
  File "C:\Users\aashu\AppData\Local\Temp\ipykernel_2624\2900835918.py", line 12, in <module>
    result = 5/0
            ~^~
ZeroDivisionError: division by zero
2025-03-13 00:49:24,739 - INFO - The program has been completed
